# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_hand_controller
    - right_hand_controller
    - left_arm_controller
    - right_arm_controller

  left_hand_controller:
    type: GripperCommand
    joints:
      - left_gripper
    action_ns: gripper_cmd
    default: true
  right_hand_controller:
    type: GripperCommand
    joints:
      - right_gripper
    action_ns: gripper_cmd
    default: true
  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
    action_ns: follow_joint_trajectory
    default: true
  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
    action_ns: follow_joint_trajectory
    default: true