# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_hand_controller:
      type: position_controllers/GripperActionController


    right_hand_controller:
      type: position_controllers/GripperActionController


    marvin_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_hand_controller:
  ros__parameters:
    joint: left_gripper
right_hand_controller:
  ros__parameters:
    joint: right_gripper
marvin_controller:
  ros__parameters:
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true